## Default values for helm-chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
#

tls:
  enabled: false
  optional: false
  keystorePass: cassandra

cassandra:
  # Mandatory docker image link
  dockerImage: ghcr.io/netcracker/cassandra_5.0:main
  install: true
  deploymentSchema:
    dataCenters:
      - name: dc1
        replicas: 3
        seeds: 2
        storage:
          size: 5Gi
  auditLogEnabled: false

  commitlogArchiving:
    enabled: false
    archive_command: /bin/cp -f %path /var/lib/cassandra/data/cl_archives/%name
    restore_command: /bin/cp -f %from %to
    restore_directories: /var/lib/cassandra/data/cl_archives/

   # Custom Cassandra configuration
  configuration: |-

  jvm_options: |-

  cassandra_env: |-

PART_OF: "cassandra"
MANAGED_BY: "cassandra"